version: "3.8"

services:
  app:
    hostname: app
    build: ./
    ports:
      - "5000:5000"
    volumes:
      - ./:/app/
    depends_on:
      - mongodb
    networks:
      - local-network
    command: "python server.py"
    environment:
      - MONGO_URI=mongodb://mongo:27017/db


  mongodb:
    hostname: mongo
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - local-network

networks:
  local-network:
    driver: bridge

volumes:
  mongodata: